[package]
name = "opencc-fmmseg-gui"
version = "0.13.0"
description = "Open Simplified/Traditional Chinese Converter"
authors = ["laisuk"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant, but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "opencc_fmmseg_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7", features = [] }

[dependencies]
tauri = { version = "2.12", features = [] }
#serde = { version = "1", features = ["derive"] }
#serde_json = "1"
#tauri-plugin-dialog = "2.6"
tauri-plugin-opener = "2.7"
#tauri-plugin-shell = "2.3.5"
opencc-fmmseg = { git = "https://github.com/laisuk/opencc-fmmseg.git", branch = "master", features = ["dictionary-build"] }
#opencc-fmmseg = {path = "../../opencc-fmmseg", features = ["dictionary-build"] }
#opencc-fmmseg = "0.13.0"
rfd = "0.17"
tauri-plugin-clipboard-manager = "2.4"
opener = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.13"
zip = { version = "=3.0", default-features = false, features = ["deflate"] }
#pdfium-helper = {path="../../pdfium-helper", features = ["pdfium-embed"] }
pdfium-helper = { git = "https://github.com/laisuk/pdfium-helper", features = ["pdfium-embed"] }
kuchiki = "0.8"
thiserror = "2.0"
quick-xml = "0.42"
encoding_rs = "0.8"
